
# Name is optional and if present must be used
# in the url path for badges
name: Create Tag

# ONLY triggers on create-external-release trigger and 
# is meant to start a new tag and update version after that
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
# Sent from: https://github.com/marketplace/actions/repository-dispatch
on: 
  repository_dispatch:
    types: [create-external-release]

jobs:

  # publish to npm on release
  # Create release action docs -> https://github.com/actions/create-release
  create-external-release:
    name: Create External Tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15]
    steps:
      - name: Checkout Public ZingGrid Repository
        uses: actions/checkout@v1
      # https://github.com/actions/create-release
      - name: Create Public Release 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        # context of environment variables
        with:
          tag_name: ${{ github.event.client_payload.version }}
          body: |            
            ## Features
            - xxxx`<zing-grid draggable` 

            ## Notable Fixes
            - IOS device multiple resize events firing causing performance issues
              
            ## New Documentation 
            - [ZingGrid Docs](https://www.zinggrid.com/docs)
          # draft true by default so it doesn't trigger the build directly
          # needs human review
          draft: true
          # public release by default
          prerelease: false