
# Name is optional and if present must be used
# in the url path for badges
name: Publish to NPM

# only run when a release has been "published"
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
on:
  release:
    types: [released]

jobs:

  # publish to npm on release
  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Update Package.json Version
        # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#create
        run: |
          git config --local user.email "admin@zingsoft.com"
          git config --local user.name "ZingSoft Admin"
          npm version ${GITHUB_REF/refs\/tags\//}
      # Will silently fail if previous package update was not run
      - name: Commit files
        run: |
          git add .
          git config --local user.email "admin@zingsoft.com"
          git config --local user.name "ZingSoft Admin"
          git commit -m "v${GITHUB_REF/refs\/tags\//}"
          git push https://zingsoftadmin:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/zinggrid/zinggrid.git
      - name: Publish Canary TagTo NPM
        if: "github.event.release.prerelease"
        run: npm publish --tag canary --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish To NPM
        if: "!github.event.release.prerelease"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
