
# Name is optional and if present must be used
# in the url path for badges
name: Publish to NPM

# only run when a tag has been "created"
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#create
on:
  create:
    tags:
      - '*'

jobs:

  # Update version
  version:
    name: Update version of lib of dev branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          ref: dev
      - name: Update Package.json Version
        # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#create
        run: |
          git config --local user.email "admin@zingsoft.com"
          git config --local user.name "ZingSoft Admin"
          npm version ${GITHUB_REF/refs\/tags\//}
      # Will silently fail if previous package update was not run
      - name: Commit files
        run: |
          git add .
          git config --local user.email "admin@zingsoft.com"
          git config --local user.name "ZingSoft Admin"
          git commit -m "v${GITHUB_REF/refs\/tags\//}"
          git push https://zingsoftadmin:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/zinggrid/zinggrid.git